{% set name = "cadCAD" %}
{% set version = "0.4.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cadCAD-{{ version }}.tar.gz
  sha256: a411f124977219d1f765164544fef0cab92601e895d687706516b8dd2d5f367f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dill
    - fn
    - funcy
    - numpy
    - pandas
    - pathos
    - python >={{ python_min }}
    - pytz
    - six

test:
  imports:
    - cadCAD
    - documentation
    - simulations
    - testing
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cadCAD-org/cadCAD
  summary: 'cadCAD: a differential games based simulation software package for research, validation, and Computer Aided Design of economic systems'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
